/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package printsalesmanager;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;


/**
 *
 * @author Xaereus
 */
public final class MainWindow extends javax.swing.JFrame{

    private final DataManager dataMan = new DataManager();

    /**
     * Creates new form MainWindow
     */
    public MainWindow(){
        initComponents();
        fullRefresh();

        table_orders.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent me){
                if(SwingUtilities.isRightMouseButton(me)){
                    int row = table_orders.rowAtPoint(me.getPoint());

                    table_orders.clearSelection();
                    table_orders.addRowSelectionInterval(row, row);
                    System.out.println("Test.");
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        dialog_newOrder = new javax.swing.JDialog();
        newOrder_label_header = new javax.swing.JLabel();
        newOrder_comboBox_customer = new javax.swing.JComboBox<>();
        newOrder_comboBox_model = new javax.swing.JComboBox<>();
        newOrder_spinner_quantity = new javax.swing.JSpinner();
        newOrder_label_quantity = new javax.swing.JLabel();
        newOrder_comboBox_year = new javax.swing.JComboBox<>();
        newOrder_comboBox_month = new javax.swing.JComboBox<>();
        newOrder_comboBox_day = new javax.swing.JComboBox<>();
        newOrder_button_newCustomer = new javax.swing.JButton();
        newOrder_button_newModel = new javax.swing.JButton();
        newOrder_label_orderedOn = new javax.swing.JLabel();
        newOrder_button_createOrder = new javax.swing.JButton();
        newOrder_button_cancelOrder = new javax.swing.JButton();
        dialog_editOrder = new javax.swing.JDialog();
        editOrder_label_header = new javax.swing.JLabel();
        editOrder_button_apply = new javax.swing.JButton();
        editOrder_button_cancel = new javax.swing.JButton();
        dialog_summary = new javax.swing.JDialog();
        dialog_newCustomer = new javax.swing.JDialog();
        newCustomer_label_header = new javax.swing.JLabel();
        newCustomer_textField_name = new javax.swing.JTextField();
        newCustomer_button_create = new javax.swing.JButton();
        newCustomer_button_cancel = new javax.swing.JButton();
        newCustomer_label_name = new javax.swing.JLabel();
        newCustomer_textField_balance = new javax.swing.JTextField();
        newCustomer_label_balance = new javax.swing.JLabel();
        dialog_newModel = new javax.swing.JDialog();
        newModel_label_header = new javax.swing.JLabel();
        newModel_button_create = new javax.swing.JButton();
        newModel_button_cancel = new javax.swing.JButton();
        newModel_scrollPane_pieces = new javax.swing.JScrollPane();
        newModel_table_pieces = new javax.swing.JTable();
        newModel_button_add = new javax.swing.JButton();
        newModel_button_removeSelected = new javax.swing.JButton();
        newModel_spinner_quantity = new javax.swing.JSpinner();
        newModel_comboBox_piece = new javax.swing.JComboBox<>();
        newModel_label_quantity = new javax.swing.JLabel();
        newModel_separator_createToRemove = new javax.swing.JSeparator();
        newModel_comboBox_filament = new javax.swing.JComboBox<>();
        newModel_button_newPiece = new javax.swing.JButton();
        newModel_button_newFilament = new javax.swing.JButton();
        dialog_newFilament = new javax.swing.JDialog();
        editOrder_label_header1 = new javax.swing.JLabel();
        editOrder_button_apply1 = new javax.swing.JButton();
        editOrder_button_cancel1 = new javax.swing.JButton();
        dialog_newPiece = new javax.swing.JDialog();
        editOrder_label_header2 = new javax.swing.JLabel();
        editOrder_button_apply2 = new javax.swing.JButton();
        editOrder_button_cancel2 = new javax.swing.JButton();
        dialog_newMaterial = new javax.swing.JDialog();
        editOrder_label_header3 = new javax.swing.JLabel();
        editOrder_button_apply3 = new javax.swing.JButton();
        editOrder_button_cancel3 = new javax.swing.JButton();
        buttonGroup_showInTable = new javax.swing.ButtonGroup();
        scrollPane_orders = new javax.swing.JScrollPane();
        table_orders = new javax.swing.JTable();
        button_newOrder = new javax.swing.JButton();
        button_editSelected = new javax.swing.JButton();
        button_showSummary = new javax.swing.JButton();
        radioButton_showAll = new javax.swing.JRadioButton();
        radioButton_showCompleted = new javax.swing.JRadioButton();
        radioButton_showIncomplete = new javax.swing.JRadioButton();
        label_show = new javax.swing.JLabel();
        menuBar_mainFrame = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menuItem_load = new javax.swing.JMenuItem();
        menuItem_save = new javax.swing.JMenuItem();
        menuItem_saveAs = new javax.swing.JMenuItem();
        menuItem_export = new javax.swing.JMenuItem();
        menu_manage = new javax.swing.JMenu();
        menuItem_customers = new javax.swing.JMenuItem();
        menuItem_filaments = new javax.swing.JMenuItem();
        menuItem_materials = new javax.swing.JMenuItem();
        menuItem_models = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menu_view = new javax.swing.JMenu();
        cbMenuItem_condForm = new javax.swing.JCheckBoxMenuItem();
        cbMenuItem_darkTheme = new javax.swing.JCheckBoxMenuItem();

        dialog_newOrder.setMinimumSize(new java.awt.Dimension(300, 280));
        dialog_newOrder.setResizable(false);

        newOrder_label_header.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        newOrder_label_header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newOrder_label_header.setText("New Order");

        newOrder_comboBox_customer.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        newOrder_comboBox_customer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer" }));

        newOrder_comboBox_model.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        newOrder_comboBox_model.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Model" }));

        newOrder_spinner_quantity.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        newOrder_label_quantity.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        newOrder_label_quantity.setText("Quantity:");

        newOrder_comboBox_year.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        newOrder_comboBox_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year" }));

        newOrder_comboBox_month.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        newOrder_comboBox_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month" }));

        newOrder_comboBox_day.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        newOrder_comboBox_day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day" }));

        newOrder_button_newCustomer.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        newOrder_button_newCustomer.setText("New");
        newOrder_button_newCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOrder_button_newCustomerActionPerformed(evt);
            }
        });

        newOrder_button_newModel.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        newOrder_button_newModel.setText("New");
        newOrder_button_newModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOrder_button_newModelActionPerformed(evt);
            }
        });

        newOrder_label_orderedOn.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        newOrder_label_orderedOn.setText("Ordered on:");

        newOrder_button_createOrder.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        newOrder_button_createOrder.setText("Create");

        newOrder_button_cancelOrder.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        newOrder_button_cancelOrder.setText("Cancel");
        newOrder_button_cancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOrder_button_cancelOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_newOrderLayout = new javax.swing.GroupLayout(dialog_newOrder.getContentPane());
        dialog_newOrder.getContentPane().setLayout(dialog_newOrderLayout);
        dialog_newOrderLayout.setHorizontalGroup(
            dialog_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newOrder_label_header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dialog_newOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialog_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_newOrderLayout.createSequentialGroup()
                        .addGroup(dialog_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newOrder_comboBox_customer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newOrder_comboBox_model, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(dialog_newOrderLayout.createSequentialGroup()
                                .addComponent(newOrder_label_quantity)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(dialog_newOrderLayout.createSequentialGroup()
                                .addComponent(newOrder_label_orderedOn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newOrder_comboBox_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newOrder_comboBox_month, 0, 80, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialog_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newOrder_comboBox_day, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newOrder_button_newCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newOrder_button_newModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newOrder_spinner_quantity, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(dialog_newOrderLayout.createSequentialGroup()
                        .addComponent(newOrder_button_cancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newOrder_button_createOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dialog_newOrderLayout.setVerticalGroup(
            dialog_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_newOrderLayout.createSequentialGroup()
                .addComponent(newOrder_label_header, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialog_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialog_newOrderLayout.createSequentialGroup()
                        .addGroup(dialog_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newOrder_comboBox_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newOrder_button_newCustomer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialog_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newOrder_comboBox_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newOrder_button_newModel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newOrder_label_quantity))
                    .addComponent(newOrder_spinner_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(dialog_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newOrder_label_orderedOn)
                    .addComponent(newOrder_comboBox_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newOrder_comboBox_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newOrder_comboBox_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialog_newOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newOrder_button_createOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(newOrder_button_cancelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        editOrder_label_header.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        editOrder_label_header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editOrder_label_header.setText("Edit Order");

        editOrder_button_apply.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        editOrder_button_apply.setText("Apply");

        editOrder_button_cancel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        editOrder_button_cancel.setText("Cancel");
        editOrder_button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editOrder_button_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_editOrderLayout = new javax.swing.GroupLayout(dialog_editOrder.getContentPane());
        dialog_editOrder.getContentPane().setLayout(dialog_editOrderLayout);
        dialog_editOrderLayout.setHorizontalGroup(
            dialog_editOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editOrder_label_header, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
            .addGroup(dialog_editOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editOrder_button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editOrder_button_apply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialog_editOrderLayout.setVerticalGroup(
            dialog_editOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_editOrderLayout.createSequentialGroup()
                .addComponent(editOrder_label_header, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addGroup(dialog_editOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editOrder_button_apply, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(editOrder_button_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout dialog_summaryLayout = new javax.swing.GroupLayout(dialog_summary.getContentPane());
        dialog_summary.getContentPane().setLayout(dialog_summaryLayout);
        dialog_summaryLayout.setHorizontalGroup(
            dialog_summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialog_summaryLayout.setVerticalGroup(
            dialog_summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        newCustomer_label_header.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        newCustomer_label_header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newCustomer_label_header.setText("New Customer");

        newCustomer_button_create.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        newCustomer_button_create.setText("Create");
        newCustomer_button_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustomer_button_createActionPerformed(evt);
            }
        });

        newCustomer_button_cancel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        newCustomer_button_cancel.setText("Cancel");
        newCustomer_button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustomer_button_cancelActionPerformed(evt);
            }
        });

        newCustomer_label_name.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        newCustomer_label_name.setText("Name:");

        newCustomer_textField_balance.setText("0");

        newCustomer_label_balance.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        newCustomer_label_balance.setText("Balance:");

        javax.swing.GroupLayout dialog_newCustomerLayout = new javax.swing.GroupLayout(dialog_newCustomer.getContentPane());
        dialog_newCustomer.getContentPane().setLayout(dialog_newCustomerLayout);
        dialog_newCustomerLayout.setHorizontalGroup(
            dialog_newCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newCustomer_label_header, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
            .addGroup(dialog_newCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialog_newCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_newCustomerLayout.createSequentialGroup()
                        .addComponent(newCustomer_button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCustomer_button_create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dialog_newCustomerLayout.createSequentialGroup()
                        .addGroup(dialog_newCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newCustomer_label_balance)
                            .addComponent(newCustomer_label_name))
                        .addGap(10, 10, 10)
                        .addGroup(dialog_newCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newCustomer_textField_name)
                            .addComponent(newCustomer_textField_balance))))
                .addContainerGap())
        );
        dialog_newCustomerLayout.setVerticalGroup(
            dialog_newCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_newCustomerLayout.createSequentialGroup()
                .addComponent(newCustomer_label_header, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(dialog_newCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCustomer_textField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCustomer_label_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialog_newCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCustomer_textField_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCustomer_label_balance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialog_newCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCustomer_button_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(newCustomer_button_create, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addContainerGap())
        );

        dialog_newModel.setMinimumSize(new java.awt.Dimension(300, 280));
        dialog_newModel.setResizable(false);

        newModel_label_header.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        newModel_label_header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newModel_label_header.setText("New Model");

        newModel_button_create.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        newModel_button_create.setText("Create");

        newModel_button_cancel.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        newModel_button_cancel.setText("Cancel");
        newModel_button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newModel_button_cancelActionPerformed(evt);
            }
        });

        newModel_table_pieces.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        newModel_table_pieces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Print", "Quantity", "Filament"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        newModel_scrollPane_pieces.setViewportView(newModel_table_pieces);

        newModel_button_add.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        newModel_button_add.setText("Add");

        newModel_button_removeSelected.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        newModel_button_removeSelected.setText("Remove Selected");

        newModel_spinner_quantity.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N

        newModel_comboBox_piece.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        newModel_comboBox_piece.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Piece" }));

        newModel_label_quantity.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        newModel_label_quantity.setText("Quantity:");

        newModel_comboBox_filament.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        newModel_comboBox_filament.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filament" }));

        newModel_button_newPiece.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        newModel_button_newPiece.setText("New");
        newModel_button_newPiece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newModel_button_newPieceActionPerformed(evt);
            }
        });

        newModel_button_newFilament.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        newModel_button_newFilament.setText("New");
        newModel_button_newFilament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newModel_button_newFilamentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_newModelLayout = new javax.swing.GroupLayout(dialog_newModel.getContentPane());
        dialog_newModel.getContentPane().setLayout(dialog_newModelLayout);
        dialog_newModelLayout.setHorizontalGroup(
            dialog_newModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newModel_label_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dialog_newModelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialog_newModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_newModelLayout.createSequentialGroup()
                        .addComponent(newModel_button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newModel_button_create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dialog_newModelLayout.createSequentialGroup()
                        .addGroup(dialog_newModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newModel_separator_createToRemove)
                            .addComponent(newModel_button_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(dialog_newModelLayout.createSequentialGroup()
                                .addGroup(dialog_newModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newModel_label_quantity)
                                    .addComponent(newModel_button_newPiece, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newModel_button_newFilament, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dialog_newModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newModel_comboBox_piece, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(newModel_comboBox_filament, 0, 132, Short.MAX_VALUE)
                                    .addComponent(newModel_spinner_quantity)))
                            .addComponent(newModel_button_removeSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newModel_scrollPane_pieces, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dialog_newModelLayout.setVerticalGroup(
            dialog_newModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_newModelLayout.createSequentialGroup()
                .addComponent(newModel_label_header, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialog_newModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newModel_scrollPane_pieces, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addGroup(dialog_newModelLayout.createSequentialGroup()
                        .addGroup(dialog_newModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newModel_comboBox_piece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newModel_button_newPiece))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialog_newModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newModel_comboBox_filament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newModel_button_newFilament))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dialog_newModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newModel_spinner_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newModel_label_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(newModel_button_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newModel_separator_createToRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newModel_button_removeSelected)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialog_newModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newModel_button_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(newModel_button_create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        editOrder_label_header1.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        editOrder_label_header1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editOrder_label_header1.setText("Edit Order");

        editOrder_button_apply1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        editOrder_button_apply1.setText("Apply");

        editOrder_button_cancel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        editOrder_button_cancel1.setText("Cancel");
        editOrder_button_cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editOrder_button_cancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_newFilamentLayout = new javax.swing.GroupLayout(dialog_newFilament.getContentPane());
        dialog_newFilament.getContentPane().setLayout(dialog_newFilamentLayout);
        dialog_newFilamentLayout.setHorizontalGroup(
            dialog_newFilamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editOrder_label_header1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
            .addGroup(dialog_newFilamentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editOrder_button_cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editOrder_button_apply1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialog_newFilamentLayout.setVerticalGroup(
            dialog_newFilamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_newFilamentLayout.createSequentialGroup()
                .addComponent(editOrder_label_header1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addGroup(dialog_newFilamentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editOrder_button_apply1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(editOrder_button_cancel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        editOrder_label_header2.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        editOrder_label_header2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editOrder_label_header2.setText("Edit Order");

        editOrder_button_apply2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        editOrder_button_apply2.setText("Apply");

        editOrder_button_cancel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        editOrder_button_cancel2.setText("Cancel");
        editOrder_button_cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editOrder_button_cancel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_newPieceLayout = new javax.swing.GroupLayout(dialog_newPiece.getContentPane());
        dialog_newPiece.getContentPane().setLayout(dialog_newPieceLayout);
        dialog_newPieceLayout.setHorizontalGroup(
            dialog_newPieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editOrder_label_header2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
            .addGroup(dialog_newPieceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editOrder_button_cancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editOrder_button_apply2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialog_newPieceLayout.setVerticalGroup(
            dialog_newPieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_newPieceLayout.createSequentialGroup()
                .addComponent(editOrder_label_header2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addGroup(dialog_newPieceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editOrder_button_apply2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(editOrder_button_cancel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        editOrder_label_header3.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        editOrder_label_header3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editOrder_label_header3.setText("Edit Order");

        editOrder_button_apply3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        editOrder_button_apply3.setText("Apply");

        editOrder_button_cancel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        editOrder_button_cancel3.setText("Cancel");
        editOrder_button_cancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editOrder_button_cancel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialog_newMaterialLayout = new javax.swing.GroupLayout(dialog_newMaterial.getContentPane());
        dialog_newMaterial.getContentPane().setLayout(dialog_newMaterialLayout);
        dialog_newMaterialLayout.setHorizontalGroup(
            dialog_newMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editOrder_label_header3, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
            .addGroup(dialog_newMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editOrder_button_cancel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editOrder_button_apply3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dialog_newMaterialLayout.setVerticalGroup(
            dialog_newMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_newMaterialLayout.createSequentialGroup()
                .addComponent(editOrder_label_header3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addGroup(dialog_newMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editOrder_button_apply3, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(editOrder_button_cancel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollPane_orders.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N

        table_orders.setAutoCreateRowSorter(true);
        table_orders.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        table_orders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer", "Date Ordered", "Model", "Quantity", "Profit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_orders.setAutoscrolls(false);
        table_orders.setColumnSelectionAllowed(true);
        table_orders.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table_orders.setName(""); // NOI18N
        scrollPane_orders.setViewportView(table_orders);
        table_orders.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        button_newOrder.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_newOrder.setText("New Order");
        button_newOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_newOrderActionPerformed(evt);
            }
        });

        button_editSelected.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_editSelected.setText("Edit Order");
        button_editSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editSelectedActionPerformed(evt);
            }
        });

        button_showSummary.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        button_showSummary.setText("Summary");
        button_showSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_showSummaryActionPerformed(evt);
            }
        });

        buttonGroup_showInTable.add(radioButton_showAll);
        radioButton_showAll.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        radioButton_showAll.setText("All");

        buttonGroup_showInTable.add(radioButton_showCompleted);
        radioButton_showCompleted.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        radioButton_showCompleted.setText("Completed");

        buttonGroup_showInTable.add(radioButton_showIncomplete);
        radioButton_showIncomplete.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        radioButton_showIncomplete.setText("Incomplete");

        label_show.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        label_show.setText("Show:");

        menuBar_mainFrame.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N

        menu_file.setText("File");
        menu_file.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N

        menuItem_load.setText("Load");
        menuItem_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_loadActionPerformed(evt);
            }
        });
        menu_file.add(menuItem_load);

        menuItem_save.setText("Save");
        menuItem_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_saveActionPerformed(evt);
            }
        });
        menu_file.add(menuItem_save);

        menuItem_saveAs.setText("Save as");
        menuItem_saveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_saveAsActionPerformed(evt);
            }
        });
        menu_file.add(menuItem_saveAs);

        menuItem_export.setText("Export");
        menuItem_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_exportActionPerformed(evt);
            }
        });
        menu_file.add(menuItem_export);

        menuBar_mainFrame.add(menu_file);

        menu_manage.setText("Manage");
        menu_manage.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N

        menuItem_customers.setText("Customers");
        menu_manage.add(menuItem_customers);

        menuItem_filaments.setText("Filaments");
        menuItem_filaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_filamentsActionPerformed(evt);
            }
        });
        menu_manage.add(menuItem_filaments);

        menuItem_materials.setText("Materials");
        menu_manage.add(menuItem_materials);

        menuItem_models.setText("Models");
        menu_manage.add(menuItem_models);

        jMenu1.setText("Customers");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        menu_manage.add(jMenu1);

        menuBar_mainFrame.add(menu_manage);

        menu_view.setText("View");
        menu_view.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N

        cbMenuItem_condForm.setSelected(true);
        cbMenuItem_condForm.setText("Conditional Formatting");
        menu_view.add(cbMenuItem_condForm);

        cbMenuItem_darkTheme.setSelected(true);
        cbMenuItem_darkTheme.setText("Dark Theme");
        cbMenuItem_darkTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMenuItem_darkThemeActionPerformed(evt);
            }
        });
        menu_view.add(cbMenuItem_darkTheme);

        menuBar_mainFrame.add(menu_view);

        setJMenuBar(menuBar_mainFrame);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(button_newOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_editSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_showSummary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(radioButton_showAll)
                    .addComponent(radioButton_showCompleted)
                    .addComponent(radioButton_showIncomplete)
                    .addComponent(label_show))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane_orders, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_newOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_editSelected)
                        .addGap(76, 76, 76)
                        .addComponent(label_show)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton_showAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton_showCompleted)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton_showIncomplete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_showSummary))
                    .addComponent(scrollPane_orders, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_filamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_filamentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem_filamentsActionPerformed

    private void cbMenuItem_darkThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMenuItem_darkThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMenuItem_darkThemeActionPerformed

    private void button_newOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_newOrderActionPerformed
        dialog_newOrder.setVisible(true);
    }//GEN-LAST:event_button_newOrderActionPerformed

    private void newOrder_button_newCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOrder_button_newCustomerActionPerformed
        dialog_newCustomer.setVisible(true);
    }//GEN-LAST:event_newOrder_button_newCustomerActionPerformed

    private void newOrder_button_newModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOrder_button_newModelActionPerformed
        dialog_newModel.setVisible(true);
    }//GEN-LAST:event_newOrder_button_newModelActionPerformed

    private void newOrder_button_cancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOrder_button_cancelOrderActionPerformed
        dialog_newOrder.setVisible(false);
    }//GEN-LAST:event_newOrder_button_cancelOrderActionPerformed

    private void newCustomer_button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustomer_button_cancelActionPerformed
        dialog_newCustomer.setVisible(false);
    }//GEN-LAST:event_newCustomer_button_cancelActionPerformed

    private void newCustomer_button_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustomer_button_createActionPerformed
        String name = newCustomer_textField_name.getText();
        Double balance = Double.parseDouble(newCustomer_textField_balance.getText());
        Customer customer = new Customer(name, balance);
        dataMan.putCustomer(customer);
        dialog_newCustomer.setVisible(false);
    }//GEN-LAST:event_newCustomer_button_createActionPerformed

    private void editOrder_button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOrder_button_cancelActionPerformed
        dialog_editOrder.setVisible(false);
    }//GEN-LAST:event_editOrder_button_cancelActionPerformed

    private void button_editSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editSelectedActionPerformed
        dialog_editOrder.setVisible(true);
    }//GEN-LAST:event_button_editSelectedActionPerformed

    private void newModel_button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newModel_button_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newModel_button_cancelActionPerformed

    private void newModel_button_newPieceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newModel_button_newPieceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newModel_button_newPieceActionPerformed

    private void newModel_button_newFilamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newModel_button_newFilamentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newModel_button_newFilamentActionPerformed

    private void button_showSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_showSummaryActionPerformed
        dialog_summary.setVisible(true);
    }//GEN-LAST:event_button_showSummaryActionPerformed

    private void menuItem_loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_loadActionPerformed
        JFileChooser jfc = new JFileChooser();

        try{
            dataMan.loadOrders();
        } catch(IOException ex){
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuItem_loadActionPerformed

    private void menuItem_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_saveActionPerformed
        // Writes all orders in the program to a DataModel and saves the model to 
        // the disk.
        try{
            dataMan.saveAll();
        } catch(IOException ex){
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuItem_saveActionPerformed

    private void menuItem_saveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_saveAsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem_saveAsActionPerformed

    /*
     * Exports all information into an Excel spreadsheet.
     */
    private void menuItem_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_exportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItem_exportActionPerformed

    private void editOrder_button_cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOrder_button_cancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editOrder_button_cancel1ActionPerformed

    private void editOrder_button_cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOrder_button_cancel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editOrder_button_cancel2ActionPerformed

    private void editOrder_button_cancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOrder_button_cancel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editOrder_button_cancel3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try{
            for(javax.swing.UIManager.LookAndFeelInfo info: javax.swing.UIManager.getInstalledLookAndFeels())
                if("Nimbus".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch(ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex){
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_showInTable;
    private javax.swing.JButton button_editSelected;
    private javax.swing.JButton button_newOrder;
    private javax.swing.JButton button_showSummary;
    private javax.swing.JCheckBoxMenuItem cbMenuItem_condForm;
    private javax.swing.JCheckBoxMenuItem cbMenuItem_darkTheme;
    private javax.swing.JDialog dialog_editOrder;
    private javax.swing.JDialog dialog_newCustomer;
    private javax.swing.JDialog dialog_newFilament;
    private javax.swing.JDialog dialog_newMaterial;
    private javax.swing.JDialog dialog_newModel;
    private javax.swing.JDialog dialog_newOrder;
    private javax.swing.JDialog dialog_newPiece;
    private javax.swing.JDialog dialog_summary;
    private javax.swing.JButton editOrder_button_apply;
    private javax.swing.JButton editOrder_button_apply1;
    private javax.swing.JButton editOrder_button_apply2;
    private javax.swing.JButton editOrder_button_apply3;
    private javax.swing.JButton editOrder_button_cancel;
    private javax.swing.JButton editOrder_button_cancel1;
    private javax.swing.JButton editOrder_button_cancel2;
    private javax.swing.JButton editOrder_button_cancel3;
    private javax.swing.JLabel editOrder_label_header;
    private javax.swing.JLabel editOrder_label_header1;
    private javax.swing.JLabel editOrder_label_header2;
    private javax.swing.JLabel editOrder_label_header3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel label_show;
    private javax.swing.JMenuBar menuBar_mainFrame;
    private javax.swing.JMenuItem menuItem_customers;
    private javax.swing.JMenuItem menuItem_export;
    private javax.swing.JMenuItem menuItem_filaments;
    private javax.swing.JMenuItem menuItem_load;
    private javax.swing.JMenuItem menuItem_materials;
    private javax.swing.JMenuItem menuItem_models;
    private javax.swing.JMenuItem menuItem_save;
    private javax.swing.JMenuItem menuItem_saveAs;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenu menu_manage;
    private javax.swing.JMenu menu_view;
    private javax.swing.JButton newCustomer_button_cancel;
    private javax.swing.JButton newCustomer_button_create;
    private javax.swing.JLabel newCustomer_label_balance;
    private javax.swing.JLabel newCustomer_label_header;
    private javax.swing.JLabel newCustomer_label_name;
    private javax.swing.JTextField newCustomer_textField_balance;
    private javax.swing.JTextField newCustomer_textField_name;
    private javax.swing.JButton newModel_button_add;
    private javax.swing.JButton newModel_button_cancel;
    private javax.swing.JButton newModel_button_create;
    private javax.swing.JButton newModel_button_newFilament;
    private javax.swing.JButton newModel_button_newPiece;
    private javax.swing.JButton newModel_button_removeSelected;
    private javax.swing.JComboBox<String> newModel_comboBox_filament;
    private javax.swing.JComboBox<String> newModel_comboBox_piece;
    private javax.swing.JLabel newModel_label_header;
    private javax.swing.JLabel newModel_label_quantity;
    private javax.swing.JScrollPane newModel_scrollPane_pieces;
    private javax.swing.JSeparator newModel_separator_createToRemove;
    private javax.swing.JSpinner newModel_spinner_quantity;
    private javax.swing.JTable newModel_table_pieces;
    private javax.swing.JButton newOrder_button_cancelOrder;
    private javax.swing.JButton newOrder_button_createOrder;
    private javax.swing.JButton newOrder_button_newCustomer;
    private javax.swing.JButton newOrder_button_newModel;
    private javax.swing.JComboBox<String> newOrder_comboBox_customer;
    private javax.swing.JComboBox<String> newOrder_comboBox_day;
    private javax.swing.JComboBox<String> newOrder_comboBox_model;
    private javax.swing.JComboBox<String> newOrder_comboBox_month;
    private javax.swing.JComboBox<String> newOrder_comboBox_year;
    private javax.swing.JLabel newOrder_label_header;
    private javax.swing.JLabel newOrder_label_orderedOn;
    private javax.swing.JLabel newOrder_label_quantity;
    private javax.swing.JSpinner newOrder_spinner_quantity;
    private javax.swing.JRadioButton radioButton_showAll;
    private javax.swing.JRadioButton radioButton_showCompleted;
    private javax.swing.JRadioButton radioButton_showIncomplete;
    private javax.swing.JScrollPane scrollPane_orders;
    private javax.swing.JTable table_orders;
    // End of variables declaration//GEN-END:variables

    public void fullRefresh(){
        refreshTable();
    }

    public void refreshTable(){

    }

}
